language: node_js
node_js:
  - 14.5
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
jobs:
  include:
    - stage: Produce Coverage
      node_js: 14.5
      script: npm run coveralls